"""Hint gating + progressive hint generation.

Per ARCHITECTURE.md §9.2 (R-14):

- Hints are NOT generated by default. The student clicks "Get a hint".
- Gate: enabled only after **≥ 2 failed graded submissions** OR
  **≥ 5 minutes since first opening** the exercise detail page.
- Progressive levels (concept → approach → code shape). Level for a
  given (handle, exercise) is the count of prior 'hint_requested'
  events for that pair, plus 1, capped at 3.
- The system prompt forbids literal compilable Python in hints.

The "first GET timestamp" is recorded once via an 'exercise_open'
event in :func:`note_exercise_opened`. Subsequent GETs do nothing.
"""

from __future__ import annotations

import json
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from bio334_checker.core import llm_call as llm_mod
from bio334_checker.core import submissions as sub_repo
from bio334_checker.core.exercises import ExerciseDetail


HINT_MIN_FAILED_ATTEMPTS = 2
HINT_MIN_SECONDS_SINCE_OPEN = 5 * 60
MAX_HINT_LEVEL = 3


class HintLevel(Enum):
    CONCEPT = 1
    APPROACH = 2
    SHAPE = 3


@dataclass
class GateState:
    allowed: bool
    reason: str
    failed_attempts: int
    seconds_since_open: Optional[int]
    next_level: int  # 1..3
    levels_consumed: int


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _iso(t: datetime) -> str:
    return t.isoformat()


def note_exercise_opened(
    conn: sqlite3.Connection, *, handle: str, exercise_slug: str, ip: str
) -> None:
    """Record the first GET timestamp for (handle, exercise). Idempotent."""
    row = conn.execute(
        "SELECT id FROM events WHERE handle=? AND event_type='exercise_open' "
        "AND detail_json LIKE ? LIMIT 1",
        (handle, f'%"slug": "{exercise_slug}"%'),
    ).fetchone()
    if row is not None:
        return
    conn.execute(
        "INSERT INTO events (ip, handle, event_type, detail_json, created_at) "
        "VALUES (?, ?, 'exercise_open', ?, ?)",
        (ip, handle, json.dumps({"slug": exercise_slug}), _iso(_now())),
    )


def _seconds_since_open(
    conn: sqlite3.Connection, *, handle: str, exercise_slug: str
) -> Optional[int]:
    row = conn.execute(
        "SELECT created_at FROM events WHERE handle=? AND event_type='exercise_open' "
        "AND detail_json LIKE ? ORDER BY id ASC LIMIT 1",
        (handle, f'%"slug": "{exercise_slug}"%'),
    ).fetchone()
    if row is None:
        return None
    opened_at = datetime.fromisoformat(row["created_at"])
    if opened_at.tzinfo is None:
        opened_at = opened_at.replace(tzinfo=timezone.utc)
    return int((_now() - opened_at).total_seconds())


def _hints_consumed(
    conn: sqlite3.Connection, *, handle: str, exercise_slug: str
) -> int:
    row = conn.execute(
        "SELECT COUNT(*) AS c FROM events WHERE handle=? "
        "AND event_type='hint_requested' AND detail_json LIKE ?",
        (handle, f'%"slug": "{exercise_slug}"%'),
    ).fetchone()
    return int(row["c"]) if row else 0


def gate_state(
    conn: sqlite3.Connection, *, handle: str, exercise_slug: str
) -> GateState:
    failed = sub_repo.count_failed_attempts(
        conn, handle=handle, exercise_slug=exercise_slug
    )
    elapsed = _seconds_since_open(conn, handle=handle, exercise_slug=exercise_slug)
    consumed = _hints_consumed(conn, handle=handle, exercise_slug=exercise_slug)
    next_level = min(consumed + 1, MAX_HINT_LEVEL)

    allowed = (
        failed >= HINT_MIN_FAILED_ATTEMPTS
        or (elapsed is not None and elapsed >= HINT_MIN_SECONDS_SINCE_OPEN)
    )

    if not allowed:
        if elapsed is None:
            reason = (
                f"Hints unlock after {HINT_MIN_FAILED_ATTEMPTS} failed submissions "
                f"or {HINT_MIN_SECONDS_SINCE_OPEN // 60} minutes of think time. "
                "Open the exercise to start the timer."
            )
        else:
            wait = max(0, HINT_MIN_SECONDS_SINCE_OPEN - elapsed)
            reason = (
                f"Hints unlock after {HINT_MIN_FAILED_ATTEMPTS} failed submissions "
                f"or {HINT_MIN_SECONDS_SINCE_OPEN // 60} minutes of think time. "
                f"Currently {failed} failed, ~{wait // 60}m remaining."
            )
    else:
        if consumed >= MAX_HINT_LEVEL:
            reason = "All three progressive hints already requested."
            allowed = False
        else:
            reason = f"Hint level {next_level}/{MAX_HINT_LEVEL} ready to request."

    return GateState(
        allowed=allowed,
        reason=reason,
        failed_attempts=failed,
        seconds_since_open=elapsed,
        next_level=next_level,
        levels_consumed=consumed,
    )


def record_hint_request(
    conn: sqlite3.Connection,
    *,
    handle: str,
    exercise_slug: str,
    level: int,
    ip: str,
) -> None:
    conn.execute(
        "INSERT INTO events (ip, handle, event_type, detail_json, created_at) "
        "VALUES (?, ?, 'hint_requested', ?, ?)",
        (
            ip,
            handle,
            json.dumps({"slug": exercise_slug, "level": level}),
            _iso(_now()),
        ),
    )


# ---------------------------------------------------------------------------
# LLM hint generation
# ---------------------------------------------------------------------------

_HINT_SYSTEM = """\
You are a hint-giver for a beginner Python programming course. Your job is
to nudge the student toward solving the exercise *without* giving them a
solution they can paste.

Hard rules:
- Never produce literal Python that compiles. No ``def`` / ``import`` /
  variable assignments / ``print(...)`` lines. Pseudocode at most.
- One short paragraph (2-4 sentences) for level 1 and 2; for level 3 you
  may include a numbered list of 3-5 conceptual steps in plain English.
- Do NOT reveal the expected output verbatim, even if it appears in the
  rubric.
- The student is a biology master's student new to Python.

Levels:
- Level 1 (Concept): identify what subskill the exercise is exercising;
  remind them which prior topic / construct it builds on.
- Level 2 (Approach): describe one valid strategy at a high level
  (e.g., "iterate over the lines, count characters, maintain a running
  total"). No code.
- Level 3 (Code shape): outline the structure with section labels but
  not literal Python. E.g., bullet points like "1. open and read the
  file as text, 2. for each line, do X, 3. after the loop, print Y".
"""


_HINT_USER_TEMPLATE = """\
Exercise: {title}
Level: {level} ({level_name})

RUBRIC
------
{rubric_md}

The student has made {failed_attempts} failed attempts so far. Stay at
the requested level — do not anticipate the next level's content.

Return ONE plain text hint (no JSON, no code fences, no Python).
"""


@dataclass
class Hint:
    level: int
    level_name: str
    text: str
    model_id: str


def generate_hint(
    *, exercise: ExerciseDetail, level: int, failed_attempts: int
) -> Hint:
    """Call the LLM for a hint. Raises :class:`llm_call.LLMError` on outage."""
    level = max(1, min(level, MAX_HINT_LEVEL))
    level_name = HintLevel(level).name.lower()

    user = _HINT_USER_TEMPLATE.format(
        title=exercise.title,
        level=level,
        level_name=level_name,
        rubric_md=exercise.rubric_md.strip(),
        failed_attempts=failed_attempts,
    )
    resp: llm_mod.LLMResponse = llm_mod.llm_call(
        user, system=_HINT_SYSTEM, max_tokens=400
    )
    return Hint(
        level=level, level_name=level_name, text=resp.text.strip(), model_id=resp.model_id
    )
